<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>shiploader_monitor</name>
  <version>0.1.0</version>
  <description>QT Widgets application for monitoring ShipLoader status via ROS2</description>
  <maintainer email="kk@example.com">kk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>km_custom_msgs</depend>
  <depend>yaml-cpp</depend>
  <depend>libqt5-dev</depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
